### ISSUE TITLE
Quebra de layout Firefox

### ISSUE THREAD

**Issue by jgaguiarm** [secultce/plugin-OpinionManagement#15]
Ao acessar uma oportunidade para visualização do parecer, ocorre uma quebra de layout na janela modal de exibição do parecer.

Navegador utilizado: Mozila Firefox 118.0.1 (64-bits).

![Captura de tela de 2024-03-21 11-53-18](https://github.com/secultce/plugin-OpinionManagement/assets/134723474/674c011f-0524-4f58-9bce-402b83921d1a)

**Comment by jgaguiarm** [comment]
Identificado que o problema está relacionado com o pseudoseletor `:has`. 
![Captura de tela de 2024-03-21 14-06-08](https://github.com/secultce/plugin-OpinionManagement/assets/134723474/e2c22b1d-879b-427e-822a-df9aa3bb9ec1)

Utilizado no CSS, linhas 45-50

```CSS
.opinion:has(.chk-collapse:checked) {
    max-height: 400px;
    overflow: auto;
}
.opinion:has(.chk-collapse:not(:checked)) {
    gap: 0;
}
```
